name: AGLHoldings
favicon: null
layout_spectrum: 0.34365362767130136
typography_spectrum: 0.00824451050721109
title: AGL Holdings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#1e222d'
    - '#415d84'
    - '#5e829c'
    - '#9daab2'
  brandStrength: 0.657174815190956
  lightness: 0.6967281480319798
  saturation: 0.9758444037288427
  rhythmicContrast: 0.407982119359076
purpose: []
